os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - '12'
  - '10'
dist: xenial
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
script:
  - ng lint
  - npm run test
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - npm run build
notifications:
  slack: es258bioelectronics:yLIXldgwMnzxiTqPY1iIbxgT
  travis encrypt "es258bioelectronics:yLIXldgwMnzxiTqPY1iIbxgT" --add notifications.slack
